= Glossary of Terms and Conventions for Product Documentation

This document (the "glossary") outlines terms and conventions for technical language in Red Hat's product documentation and other technical content. These terms and conventions supplement those in _The IBM Style Guide_, which is the main reference for technical terms.

== Compiled Version

link:https://redhat-documentation.github.io/glossary-of-terms-and-conventions-for-product-documentation/[Glossary of Terms and Conventions for Product Documentation]

== Looking for Guidance?

If you are looking for guidance that is not in the glossary or _The IBM Style Guide_, you can submit your question as a link:https://github.com/redhat-documentation/glossary-of-terms-and-conventions-for-product-documentation/issues[GitHub issue] and the project team will discuss and come to a consensus. See link:https://redhat-documentation.github.io/glossary-of-terms-and-conventions-for-product-documentation/#submitting_issues[Submitting Issues] for more information.

== Contributing

See link:https://redhat-documentation.github.io/glossary-of-terms-and-conventions-for-product-documentation/#how_to_update_this_document[How to Update this Document] for details.

== Project Members

=== Ongoing Project Contributors and Repository Maintainers

These project members continue to work on project team, and maintain the repository on an ongoing basis via the Documentation Conventions Repository Administration Roster.

Feel free to contact these project members with questions about and suggestions for the project or the repository.

Andrea Hoffer (ahoffer@redhat.com)

Andrew Dahms (adamhs@redhat.com)

Chris Budzilowicz (cbudzilo@redhat.com)

Ingrid Towey (itowey@redhat.com)

Jennifer Malloy (jmalloy@redhat.com)

Les Williams (lwilliam@redhat.com)

Tahlia Richardson (trichard@redhat.com)

=== Initial Project Contributors

These project members contributed to the setup phase of the project, and the original content of the glossary.

Andrea Hoffer (ahoffer@redhat.com)

Andrew Dahms (adamhs@redhat.com)

Bára Ančincová (bara@redhat.com)

Chris Budzilowicz (cbudzilo@redhat.com)

David Michael (dmichael@redhat.com)

Ingrid Towey (itowey@redhat.com)

Jennifer Malloy (jmalloy@redhat.com)

Les Williams (lwilliam@redhat.com)

Lucy Bopf (lbopf@redhat.com)

Nichola Moore (nmoore@redhat.com)

Tahlia Richardson (trichard@redhat.com)
