= Glossary of Terms and Conventions for Product Documentation

This document outlines terms and conventions for technical language in Red Hat's product documentation and other technical content. These terms and conventions supplement those in _The IBM Style Guide_, which is the main reference for technical terms. 

== Compiled Version

http://ccs-jenkins.gsslab.brq.redhat.com:8080/job/glossary-of-terms-and-conventions-for-product-documentation-branch-master/lastSuccessfulBuild/artifact/index.html[Glossary of Terms and Conventions for Product Documentation]

== Contributing

See http://ccs-jenkins.gsslab.brq.redhat.com:8080/job/glossary-of-terms-and-conventions-for-product-documentation-branch-master/lastSuccessfulBuild/artifact/index.html#how_to_update_this_document[How to Update this Document] for details.

== Project Members

=== Ongoing Project Contributors and Repository Maintainers

These project members continue to work on project team, and maintain the repository on an ongoing basis via the https://calendar.google.com/calendar/embed?src=redhat.com_gnjpmdsmror0bai9p0sdgfn8bc%40group.calendar.google.com&ctz=Australia/Brisbane[Documentation Conventions Repository Administration Roster].

These project members can be contacted with questions about and suggestions for the project or the repository.

Andrea Hoffer (ahoffer@redhat.com)

Andrew Dahms (adamhs@redhat.com)

Bára Ančincová (bara@redhat.com)

Chris Budzilowicz (cbudzilo@redhat.com)

Ingrid Towey (itowey@redhat.com)

Jennifer Malloy (jmalloy@redhat.com)

Les Williams (lwilliam@redhat.com)

Lucy Bopf (lbopf@redhat.com)

Tahlia Richardson (trichard@redhat.com)

=== Initial Project Contributors

These project members contributed to the setup phase of the project, and the original content of the _Glossary_.

Andrea Hoffer (ahoffer@redhat.com)

Andrew Dahms (adamhs@redhat.com)

Bára Ančincová (bara@redhat.com)

Chris Budzilowicz (cbudzilo@redhat.com)

David Michael (dmichael@redhat.com)

Ingrid Towey (itowey@redhat.com)

Jennifer Malloy (jmalloy@redhat.com)

Les Williams (lwilliam@redhat.com)

Lucy Bopf (lbopf@redhat.com)

Nichola Moore (nmoore@redhat.com)

Tahlia Richardson (trichard@redhat.com)
