[discrete]
==== taskbar
[[taskbar]]
Description: Use taskbar as one word. Do not use task bar.
Use it: yes
Class: noun
Incorrect forms: task bar
See also:

[discrete]
==== tar, tarball
[[tar]]
Description: Do not use to refer to creating a tar file. Instead use a verb, example: archive or archive.
Use it: no
Class: verb
Incorrect forms:
See also:

[discrete]
==== tarball
[[tarball]]
Description: Do not use. Instead use tar file.
Use it: no
Class: noun
Incorrect forms:
See also:

[discrete]
==== telephone numbers
[[telephone_numbers]]
Description: Use spaces, not dashes or dots, to punctuate phone numbers. When indicating a number for international use, include the country code (+1 555 555 5555 for a US number, for example). US 800 numbers are not accessible from outside the country, so do not precede them with a country code (800 555 5555). Phone numbers beginning with 0 are not for international use. Make these numbers ready for international by dropping the zero and adding the appropriate country code. For example, (055) 12345 would be for use in Italy only; change it to +39 (55) 12345 for international use. 
Use it: yes
Class: 
Incorrect forms: +1.555.555.5555, +1-555-555-5555
See also:

[discrete]
==== terminal
[[terminal]]
Description: Do not use to describe where to type commands. Use "command line" instead. See the Word Usage appendix of The IBM Style Guide for more information. 
Use it: no
Class: noun
Incorrect forms:
See also:

[discrete]
==== terminal emulation
[[terminal_emulation]]
Description: Refers to making a computer respond like a particular type of terminal. Terminal emulation programs allow you to access a mainframe computer or bulletin board service with a personal computer. 
Use it: yes
Class:
Incorrect forms:
See also:

[discrete]
==== ⁠text mode
[[text_mode]]
Description: Correct. A video mode in which a display screen is divided into rows and columns of boxes. Each box can contain one character. Text mode is also called character mode. 
Use it: yes
Class:
Incorrect forms: textmode, text-mode
See also:

[discrete]
==== text-based
[[text-based]]
Description: Correct. 
Use it: yes
Class: adjective
Incorrect forms: text based
See also:

[discrete]
==== ⁠third-party
[[third-party]]
Description: Use "third-party" as the adjectival form. Consult a dictionary for more examples. 
Use it: yes
Class: adjective
Incorrect forms:
See also:

[discrete]
==== third party
[[third_party]]
Description: Use "third party" as the nominal form. Consult a dictionary for more examples. 
Use it: yes
Class: noun
Incorrect forms:
See also:

[discrete]
==== through
[[through]]
Description: Correct. Do not use the hyphen or any other type of dash. 
Use it: yes
Class: noun
Incorrect forms: thru
See also:

[discrete]
==== throughput
[[throughput]]
Description: The amount of data transferred from one place to another or processed in a specified amount of time. Data transfer rates for disk drives and networks are measured in terms of throughput. Typically, throughput is measured in kbps, Mbps, or Gbps. See The IBM Style Guide for more information about using measurements and abbreviations.
Use it: yes
Class: noun
Incorrect forms: thru
See also:

[discrete]
==== tier-1
[[tier-1]]
Description: Always use a numeral, and always hyphenate. Follow standard capitalization guidelines. 
Use it: yes
Class: adjective
Incorrect forms: tier-one, tier 1
See also:

[discrete]
==== time frame
[[time_frame]]
Description: Correct.  
Use it: yes
Class: noun
Incorrect forms: timeframe, time-frame
See also:

[discrete]
==== time zone
[[time_zone]]
Description: Correct.  
Use it: yes
Class: noun
Incorrect forms: timezone, time-zone
See also:

[discrete]
==== token ring
[[token_ring]]
Description: When capitalized, Token Ring refers to the PC network architecture developed by IBM. The IBM Token-Ring specification has been standardized by the IEEE as the IEEE 802.5 standard. See The IBM Style Guide for further uses of this term.   
Use it: yes
Class: noun
Incorrect forms:
See also:

[discrete]
==== ⁠toolbar
[[toolbar]]
Description: Correct. 
Use it: yes
Class: noun
Incorrect forms: tool bar, tool-bar
See also:

[discrete]
==== ⁠totally
[[totally]]
Description: Do not use. See basically.
Use it: no
Class: 
Incorrect forms:
See also:

[discrete]
==== ⁠⁠troubleshoot
[[troubleshoot]]
Description: Correct.
Use it: yes
Class: verb
Incorrect forms: trouble shoot, trouble-shoot
See also:

[discrete]
==== TTL
[[TTL]]
Description: Initialism for "time to live" (noun) and "time-to-live" (adjective). Neither the noun nor the adjective should be capitalized unless you are documenting a GUI field, label, or similar element, in which case you should use the same capitalization. Capitalization at the beginning of a sentence is acceptable. The initialism is always uppercase. 
Use it: yes
Class: verb
Incorrect forms: ttl
See also:

[discrete]
==== ⁠type
[[type]]
Description: Type can be used as either a verb or noun. You can write "Print the data type of init" or "To start Source-Navigator, *type snavigator*." 
Use it: yes
Class: verb, noun
Incorrect forms:
See also: