[discrete]
==== UID
[[UID]]
Description: UID and User ID are abbreviations of user identifier.
Use it: yes
Class: noun
Incorrect forms: uid
See also:

[discrete]
==== ⁠UltraSPARC
[[UltraSPARC]]
Description: Correct.  UltraSPARC is a trademark of SPARC International, Inc., and is used under license by Sun Microsystems, Inc. Products bearing the SPARC trademarks are based upon an architecture developed by Sun Microsystems, Inc. 
Use it: yes
Class: noun
Incorrect forms: ULTRASPARC, UltraSparc, or other variations.
See also:

[discrete]
==== ⁠uninterruptible
[[uninterruptible]]
Description: Despite not appearing in the American Heritage Dictionary, this term does appear in the Merriam-Webster Unabridged Dictionary, and is considered acceptable in Red Hat documentation, especially in the context of "uninterruptible power supply (UPS)." 
Use it: yes
Class: adjective
Incorrect forms:
See also:

[discrete]
==== ⁠UNIX
[[UNIX]]
Description: Correct. UNIX is a registered trademark of The Open Group. Do not use "UNIX-like", instead use an expression such as "Linux, UNIX, and similar operating systems" instead. 
Use it: yes
Class: noun
Incorrect forms: Unix, unix
See also:

[discrete]
==== ⁠unset
[[unset]]
Description: Use "Clear" instead. For example: To disable the *Wobbly Widget*, clear the *Enable Wobbly Widget* check box. Another example:  This rule only matches TCP packets that have the SYN flag set and the ACK flag cleared. 
Use it: no
Class: verb
Incorrect forms:
See also:

[discrete]
==== ⁠untrusted
[[untrusted]]
Description: Use only in the context of security relationships. For example, web browsers often indicate that a site is "untrusted" if it cannot verify that site's security certificate. 
Use it: yes
Class: adjective
Incorrect forms:
See also:

[discrete]
==== ⁠upgrade
[[upgrade]]
Description: Correct.
Use it: yes
Class: verb
Incorrect forms: up-grade, up grade
See also:

[discrete]
==== ⁠UPS
[[UPS]]
Description: Abbreviation of uninterruptible power supply, a power supply that includes a battery to maintain power in the event of a power outage. 
Use it: yes
Class: 
Incorrect forms:
See also:

[discrete]
==== ⁠upsell
[[upsell]]
Description: Definition as per htp://www.ahdictionary.com/word/search.html?q=upsell: The practice of offering customers additional or more expensive products or services after they have already agreed to buy something. No adjectival form is currently recognized.  
Use it: yes
Class: verb
Incorrect forms: up-sell
See also:

[discrete]
==== upselling
[[upselling]]
Description: Definition as per htp://www.ahdictionary.com/word/search.html?q=upsell: The practice of offering customers additional or more expensive products or services after they have already agreed to buy something. No adjectival form is currently recognized.  
Use it: yes
Class: noun
Incorrect forms: up-selling, up selling
See also:

[discrete]
==== ⁠upstream
[[upstream]]
Description: Correct. Use the one-word form for both the nominal and adjectival forms. 
Use it: yes
Class: noun, adjective
Incorrect forms: up-stream, up stream
See also: See also downstream. 

[discrete]
==== ⁠uptime
[[uptime]]
Description: Use one-word form.
Use it: yes
Class: noun
Incorrect forms: up-time, up time 
See also:

[discrete]
==== URL
[[URL]]
Description: Include the appropriate protocol, such as http, ftp, or https, at the beginning of URLs. That is, use http://www.redhat.com and not www.redhat.com. 
Use it: yes
Class: noun
Incorrect forms: 
See also: See Referencing Other Internet Sites for more information. 

[discrete]
==== ⁠usable
[[usable]]
Description: Correct.
Use it: yes
Class: adjective
Incorrect forms: useable
See also:

[discrete]
==== ⁠user
[[user]]
Description: When referring to the reader, use "you" instead of "user." For example, "The user must..." is incorrect. Use "You must..." instead. If referring to more than one user, calling the collection "users" is acceptable, such as "Other users may wish to access your database." 
Use it: no
Class: noun
Incorrect forms:
See also:

[discrete]
==== ⁠⁠userid
[[userid]]
Description: Acceptable abbreviation of user identifier. 
Use it: yes
Class: noun
Incorrect forms:
See also:

[discrete]
==== ⁠user interface
[[user_interface]]
Description: Correct. The junction between a user and a computer program. An interface is a set of commands or menus through which a user communicates with a program. A command-driven interface is one in which you enter commands. A menu-driven interface is one in which you select command choices from various menus displayed on the screen. 
Use it: yes
Class: noun
Incorrect forms: user-interface, userinterface
See also:

[discrete]
==== user name
[[user_name]]
Description: Correct. Do not use "username" unless you are using it as a variable. 
Use it: yes
Class: noun
Incorrect forms:
See also:

[discrete]
==== user space
[[user_space]]
Description: Correct when used as a noun. When used as a modifier, use the hyphenated form, "user-space."
Use it: yes
Class: noun
Incorrect forms: userspace
See also:

[discrete]
==== ⁠⁠utilize
[[utilize]]
Description: Avoid this term. Write "use" instead. 
Use it: no
Class: noun
Incorrect forms:
See also:
