[[template]]
Use the following template to describe particular entries:

The AsciiDoc source:

----
[discrete]
==== <term>
[[<anchor-tag>]]
*Description*: <description>

*Use it*: <yes/no/with caution>

*Class*: <class>

*Incorrect forms*: <incorrect-form>

*See also*: xref:<another-anchor-tag>[<another-term>]
----

Replace:

* `<term>` with the term to be described
* `<anchor-tag>` with the term in lowercase, if the term consists of more than one word, separate them with a hyphen ("-"). Don't use spaces, capital letters, or special characters (e.g., slash /) in this name. If two entries would have a same anchor tag, see xref:two-entries-with-same-anchor-tag[What to do if two entries have the same anchor tag?.]
* `<description>` with the description of the term and why should we use it in this form and why are the incorrect forms incorrect, or why we should not use the term
* `<yes/no/with caution>` with `yes`, `no`, or `with caution` depending on whether the term should be used, not be used, or used with caution. Always explain why in the *Description* field
* `<class>` with the class of the term (noun, adjective, verb, ...)
* `<incorrect-form>` with the form of the term that we should not use. If there are more than one, separate them with a comma (",")
* `<another-anchor-tag>` with the anchor tag of the another term related to this one
* `<another-term>` with the term related to this one

For example:

----
[discrete]
==== Ceph
[[ceph]]
*Description*: Ceph is a unified, distributed storage system designed for excellent performance, reliability and scalability. The Red Hat offering of Ceph is called Red Hat Ceph Storage. Do not use "CEPH" because it is not an acronym. Use "ceph" only when referring to the `ceph` command and as such, mark it properly.

*Use it*: yes

*Class*: noun

*Incorrect forms*: CEPH, ceph

*See also*: xref:red-hat-ceph-storage[Red Hat Ceph Storage]
----

For the rendered output see xref:ceph[Ceph].

[NOTE]
====
If the term has the correct and incorrect form, always use the correct form instead of `<term>` and list the incorrect form in the *Incorrect forms* field. Remember to explain why is the incorrect form incorrect in the *Description* field.

If you want to add a term that we should not use and that does not have a correct form, use the incorrect version instead of `<term>` and add "no" to the *Use it* field. Explain why we should not use that term in the *Description* field.
====
