[[template-for-entries]]
Use the following template to describe particular entries:

The AsciiDoc source:

----
[discrete]
==== <term> (<class>)
[[<id>]]
*Description*: <description>

*Use it*: <yes/no/with caution>

*Incorrect forms*: <incorrect-form>

*See also*: xref:<another-term-id>[<another-term>]
----

[width="40%",frame="topbot",options="header"]
|======================
|Replace                |With                               | Notes
|`<term>`               |The term to be described.          |
|`<id>`                 |The term in lowercase.             |If the term consists of more than one word, separate them with a hyphen ("-"). Do not use spaces, capital letters, or special characters (for example, slash "/") in the ID. If two entries would have the same ID, see xref:two-entries-with-same-ID[What to do if two entries have the same ID?.]
|`<description>`        |The description of the term.|Use full sentences with periods. If a term has more than one meaning, use numbers to separate them. See the xref:media[media] entry for an example. Add information why should we use the term in this form. If we should not use the term, explain why. Alternatively, explain why are the terms listed in the *Incorrect forms* field incorrect.
|`<yes/no/with caution>`|"yes" if the term should be used.

"no" if the term should not be used.

"with caution" if the term should be used sporadically or only in certain cases.|Explain why we should or should not use the term in the *Description* field.
|`<class>`              |The figure of speech of the term.|Possible values: noun, verb, adjective, adverb, pronoun, conjunction, preposition. Use noun also for acronyms or abbreviations. Leave the field empty for symbols.
|`<incorrect-form>`     |The form of the term that we should not use.|If there are multiple incorrect forms, separate them with a comma (",").
|`<another-term-id>`    |The ID of another term related to this one.|Always verify that this ID already exists in the document. The document fails to validate because of non-existent IDs. Do not put space between `<another-term-id>` and `[<another-term>]`.
|`<another-term>`       |The term related to this one.|To link to another document than this one or to a web page, replace `xref:<another-term-id>[<another-term>]` with `<link>[<name-of-the-document/web-page>]`.
|======================

[IMPORTANT]
====
* Do not combine two terms into one entry.

* Keep all fields, even if a field is empty. An empty field serves as a placeholder if the field is required later.

* If the term has the correct and incorrect form, always use the correct form instead of `<term>` and list the incorrect form in the *Incorrect forms* field. Remember to explain why the incorrect form is incorrect in the *Description* field.

* If you want to add a term that we should not use and that does not have a correct form, use the incorrect version instead of `<term>` and add "no" to the *Use it* field. Explain why we should not use that term in the *Description* field.

* If you want to list a term in the _Product-specific Conventions_ chapter that is already included in the _General Conventions_ chapter, add the product-specific meaning to the *Description* field of the term in _General Conventions_. Use numbers to separate the meanings. In _Product-specific Conventions_ add the following boilerplate text with the link to the entry in _General Conventions_:
+
----
==== <term> (<class>)
See xref:<id-in-general-conventions>[<term>] in the _General Conventions_ part.
----
====

.Example
----
[discrete]
==== Ceph (noun)
[[ceph]]
*Description*: Ceph is a unified, distributed storage system designed for excellent performance, reliability and scalability.

*Use it*: yes

*Incorrect forms*: CEPH, ceph

*See also*: xref:red-hat-ceph-storage[Red Hat Ceph Storage]
----

For the rendered output see xref:ceph[Ceph].
