[[template]]
Use the following template to describe particular entries:

The AsciiDoc source:

----
[discrete]
==== <term>
[[<anchor-tag>]]
*Description*: <description>

*Use it*: <yes/no/with caution>

*Class*: <noun/adjective/verb/adverb>

*Incorrect forms*: <incorrect-form>

*See also*: xref:<another-anchor-tag>[<another-term>]
----

[width="40%",frame="topbot",options="header"]
|======================
|Replace                |with                       | Notes 
|`<term>`               |the term to be described.  | 
|`<anchor-tag>`         |the term in lowercase.|If the term consists of more than one word, separate them with a hyphen ("-"). Do not use spaces, capital letters, or special characters (for example, slash "/") in the anchor tag. If two entries would have the same anchor tag, see xref:two-entries-with-same-anchor-tag[What to do if two entries have the same anchor tag?.]
|`<description>`        |the description of the term.|Add information why we should we use it in this form and why are the incorrect forms incorrect, or why we should not use the term. Use full sentences with periods. If a term has more than one meaning, use numbers to separate them. See the xref:media[media] entry for an example.
|`<yes/no/with caution>`|"yes" if the term should be used, "no" if the term should not be used, or "with caution" if the term should be used sporadically or only in certain cases.|Explain why should or should not use the term in the *Description* field.
|`<class>`              |the figure of speech of the term (noun, adjective, verb, adverb).|For acronyms, abbreviations, or initializations use "noun". Leave the field empty for symbols. 
|`<incorrect-form>`     |the form of the term that we should not use.|If there are more than one, separate them with a comma (",").
|`<another-anchor-tag>` |the anchor tag of another term related to this one.| 
|`<another-term>`       |the term related to this one.|
|======================

[IMPORTANT]
====
Keep all fields, even if a field is empty. It will be a placeholder if the field is required at a later date.
====

[NOTE]
====
If the term has the correct and incorrect form, always use the correct form instead of `<term>` and list the incorrect form in the *Incorrect forms* field. Remember to explain why is the incorrect form incorrect in the *Description* field.

If you want to add a term that we should not use and that does not have a correct form, use the incorrect version instead of `<term>` and add "no" to the *Use it* field. Explain why we should not use that term in the *Description* field.
====

.Example
----
[discrete]
==== Ceph
[[ceph]]
*Description*: Ceph is a unified, distributed storage system designed for excellent performance, reliability and scalability. The Red Hat offering of Ceph is called Red Hat Ceph Storage. Do not use "CEPH" because it is not an acronym. Use "ceph" only when referring to the `ceph` command and as such, mark it properly.

*Use it*: yes

*Class*: noun

*Incorrect forms*: CEPH, ceph

*See also*: xref:red-hat-ceph-storage[Red Hat Ceph Storage]
----

For the rendered output see xref:ceph[Ceph].
