[[how-to-update-this-document]]

This guide is written in the AsciiDoc markup language and hosted in a git repository at https://gitlab.cee.redhat.com/ccs-internal-documentation/documentation-conventions[GitLab].

NOTE: Before you start, ensure that you are logged in to GitLab.

.Add or Edit General Conventions:

. Create a new branch.

    .. On the main repository page (https://gitlab.cee.redhat.com/ccs-internal-documentation/glossary-of-terms-and-conventions-for-product-documentation/tree/master) click the plus button and select "New branch".

    .. Specify the name of the branch. Use the "wip-<name-of-the-entry>" form when adding a new entry, for example "wip-host-name" or "wip-<name-of-the-entry-edits>" when updating an existing entry, for example "wip-host-name-edits".

    .. Click "Create branch".

. Make edits in the guide.

    .. Navigate to the `general_conventions` directory and select the file you want to add the entry to.

    .. Ensure that you are in the correct branch. The branch name is listed at the beginning of the path to the file. If you are not in the correct branch, select it from the menu.

    .. Click "Edit".

    .. Make the changes. Use this xref:template[template] when adding a new entry.

. Commit the changes

    .. Update the commit message. Be descriptive enough, "Updated the <filename> file." is not a good commit message. Use something like "Added the <entry-name> entry or "Fixed a typo in the <entry-name> entry.

    .. Click "Commit Changes"

. If you want to make additional changes, edit the file again and commit the changes.

. Once you are done updating the file, create a merge request.

    .. Click "Create Merge Request".

    .. Click "Remove the WIP: prefix from the title".

    .. Optionally, write a description of your change.

    .. Click "Submit merge request".

.Add or Edit Product-Specific Conventions

. Create a new branch.

    .. On the main repository page (https://gitlab.cee.redhat.com/ccs-internal-documentation/glossary-of-terms-and-conventions-for-product-documentation/tree/master) click the plus button and select "New branch".

    .. Specify the name of the branch. Use the "wip-<name-of-the-entry>" form when adding a new entry or file, for example "wip-self-hosted-engine", or "wip-<name-of-the-entry-edits>" when updating an existing entry, for example "wip-self-hosted-engine-edits".

    .. Click "Create branch".

. Make edits in the guide.

    .. Navigate to the `products_conventions` directory and select the file you want to add the entry to. If a file for the product does not exist yet, create one. Use the "<product-name>.adoc" form, for example "red-hat-virtualization.adoc".

    .. Ensure that you are in the correct branch. The branch name is listed at the beginning of the path to the file. If you are not in the correct branch, select it from the menu.

    .. Click "Edit".

    .. Make the changes. Use the https://gitlab.cee.redhat.com/ccs-internal-documentation/glossary-of-terms-and-conventions-for-product-documentation/blob/master/general_information/template.adoc[template] when adding a new entry. Entries must be added in alphabetical order.

    .. If you created a new file, add the file as an include in the `master.adoc` file. Add the file in alphabetical order under the `== Product-specific Conventions` heading. For example:
+
[source]
----
 include::{includedir}/products_conventions/red-hat-virtualization.adoc[]
----
+

. Commit the changes

    .. Update the commit message. Be descriptive enough, "Updated the <filename> file." is not a good commit message. Use something like "Added the <entry-name> entry or "Fixed a typo in the <entry-name> entry".

    .. Click "Commit Changes"

. If you want to make additional changes, edit the file again and commit the changes.

. Once you are done updating the file, create a merge request.

    .. Click "Create Merge Request".

    .. Click "Remove the WIP: prefix from the title".

    .. Optionally, write a description of your change.

    .. Click "Submit merge request".


