[[how-to-update-this-document]]

This document is written in the AsciiDoc markup language and hosted in a git repository at https://gitlab.cee.redhat.com/ccs-internal-documentation/glossary-of-terms-and-conventions-for-product-documentation[GitLab].

You can edit this document by using:

* The GitLab web user interface. See xref:web-ui-adding-or-editing-entries[Web UI: Adding and Editing Entries] for details.
* The `git` command-line utility. See xref:cli-adding-and-editing-entries[CLI: Adding and Editing Entries]. Previous experience with `git` and the command line is required.

Once you are done with the edits, create a merge request. See xref:creating-merge-requests[Creating Merge Requests] for details.

[[web-ui-adding-or-editing-entries]]
[discrete]
==== Web UI: Adding and Editing Entries

NOTE: Before you start, ensure that you are logged in to GitLab. Use your Kerberos credentials or the Red Hat SAML Login to log in to GitLab.

. Create a new branch.

    .. On the main repository page (https://gitlab.cee.redhat.com/ccs-internal-documentation/glossary-of-terms-and-conventions-for-product-documentation/tree/master) click the plus button and select "New branch".

    .. Specify the name of the branch. Use the "wip-<name-of-the-entry>" form when adding a new entry, for example "wip-host-name" or "wip-<name-of-the-entry-edits>" when updating an existing entry, for example "wip-host-name-edits".

    .. Click "Create branch".

. Edit the document.

    .. Navigate to the `general_conventions` or `product_conventions` directory and select the file you want to add the entry to. If a file for the product does not exist yet, create one. Use the "<product-name>.adoc" form, for example "red-hat-virtualization.adoc".

    .. Ensure that you are in the correct branch. The branch name is listed at the beginning of the path to the file. If you are not in the correct branch, select it from the menu.

    .. Click "Edit".

    .. Make the changes. Use this xref:template[template] when adding a new entry. Entries must be added in alphabetical order.

    .. If you created a new file, add the file to the `master.adoc` file. Add the file in alphabetical order under the `== Product-specific Conventions` heading. For example:
+
[source]
----
 include::{includedir}/products_conventions/red-hat-virtualization.adoc[]
----

. Commit the changes

    .. Update the commit message. Be descriptive enough, "Updated the <filename> file." is not a good commit message. Use something like "Added the <entry-name> entry or "Fixed a typo in the <entry-name> entry".

    .. Click "Commit Changes"

. If you want to make additional changes, edit the file again and commit the changes.

. Make sure that the AsciiDoc source code is valid.

    .. Navigate to the http://ccs-jenkins.gsslab.brq.redhat.com/TopicBranches#glossary-of-terms-and-conventions-for-product-documentation[Glossary of Terms and Conventions for Product Documentation] Jenkins job.

    .. Wait till the branch you created appears in the list. It should not take more than 10 minutes. 

    .. Verify that "yes" is listed in the "Success build?" column. See xref:preview-of-changes[Where can I view the changes I made?] and xref:failed-jenkins-build[What to do when Jenkins fails to build the document after I added my changes?] for details.

. Once you are done updating the document, create a merge request. See xref:creating-merge-requests[Creating Merge Requests] for details.

[[cli-adding-and-editing-entries]]
[discrete]
==== CLI: Adding and Editing Entries

[NOTE]
====
This procedure requires `git` and `ccutil` installed. See https://pantheon-ccstools.itos.redhat.com/help/user-guide/#ccutil-install[Installing ccutil] for details.
====

. If you do not have a local copy of the `glossary-of-terms-and-conventions-for-product-documentation` git repository, clone it.
+
----
$ git clone git@gitlab.cee.redhat.com:ccs-internal-documentation/glossary-of-terms-and-conventions-for-product-documentation.git
----

. Navigate to the cloned repository.
+
----
$ cd glossary-of-terms-and-conventions-for-product-documentation
----

. If you have a local copy already, pull the latest changes.
+
----
$ git pull --rebase
----

. Create a new branch. When adding a new entry, use "wip-<name-of-the-entry>" as the branch name, for example "wip-host-name". When updating an existing entry, use "wip-<name-of-the-entry-edits>" as the branch name, for example "wip-host-name-edits".
+
----
$ git checkout -b <name-of-the-branch>
----

. Edit the document.

    .. Navigate to the `general_conventions` or `products_conventions` directory and open the file you want to add the entry to. If a file for the product does not exist yet, create one. Use the "<product-name>.adoc" form, for example "red-hat-virtualization.adoc".

    .. Make the changes. Use this xref:template[template] when adding a new entry. Entries must be added in alphabetical order.

    .. If you created a new file, add the file to the `master.adoc` file. Add the file in alphabetical order under the `== Product-specific Conventions` heading. For example:
+
[source]
----
 include::{includedir}/products_conventions/red-hat-virtualization.adoc[]
----

. Verify that you are able to build the document locally. Run the following command from the main repository directory (the one where the `master.adoc` file is).
+
----
$ ccutil compile --format html-single --lang en-US --open
----
+
If `ccutil` fails to build the document, fix the reported errors. See xref:failed-jenkins-build[What to do when Jenkins fails to build the document after I added my changes?] for additional hints.

. Stage the changes.
+
----
$ git add <file>
----

. Commit the changes. Be descriptive enough in the commit message, "Updated the <filename> file." is not a good commit message. Use something like "Added the <entry-name> entry or "Fixed a typo in the <entry-name> entry".
+
----
$ git commit -m "<commit-message>"
----

. Push the changes.
+
----
$ git push --set-upstream origin <name-of-the-branch>
----

. Once you are done updating the document, create a merge request. See xref:creating-merge-requests[Creating Merge Requests] for details.

[[creating-merge-requests]]
[discrete]
==== Creating Merge Requests

. Navigate to the main repository page (https://gitlab.cee.redhat.com/ccs-internal-documentation/glossary-of-terms-and-conventions-for-product-documentation/tree/master) and click "Merge Requests".

. Click "New Merge Request".

. Select the source branch from the drop-down list.

. Click "Compare branches and continue".

. Click "Remove the WIP: prefix from the title".

. Optionally, write a description of your change.

. Select the correct label; _General Conventions_ or _Product-Specific Conventions_.

. Click "Submit merge request".
